services:
    db:
        image: postgres
        restart: unless-stopped
        container_name: postgres-task-manager
        environment:
            POSTGRES_USER: richglez
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: task_manager_db
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql  # <- sin /data en Postgres 18
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U richglez -d task_manager_db']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
